plugins {
    id 'com.android.application'
}

android {
    namespace 'cloud.kasmui.statistika'
    compileSdk 34

    defaultConfig {
        applicationId 'cloud.kasmui.statistika'
        minSdk 23
        targetSdk 34
        versionCode 100
        versionName '1.0.0'
    }

    buildTypes {
        debug { minifyEnabled false }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
